services:
  nodeapp:
    image: node:lts
    container_name: qris-pay-noti
    volumes:
      - nodeapp-data:/usr/src/app
    restart: always
    networks:
      - dokploy-network
    entrypoint: /bin/sh -c "npm install && npm start"

networks:
  dokploy-network:
    external: true

volumes:
  nodeapp-data:
