networks:
  dokploy-network:
    external: true
services:
  nodeapp:
    image: node:lts
    container_name: qris-pay-noti
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      - NODE_ENV=production
    entrypoint: /bin/sh -c "npm install && npm start"
